### ISSUE TITLE
Compiling DCX documentation

### ISSUE THREAD

**Issue by warrenarea** [twig/dcxdll#10]
For anyone out there struggling to compile their own DCX, perhaps this will help.

Using Visual Studio 2012, you open the solutions project.

You will need to have "DirectX SDK June 2010" installed, otherwise
you will get an error from  
```
#ifdef DCX_USE_DXSDK
#include <Dxsdkver.h>
```

You will also have to change the Project -> Properties -> Post-Build / Pre-Build options
to reflect your own mIRC folder.
(To simplify things, I used the same DELETE/COPY settings of dcx.dll in the release post/pre build options as were in the debug profile.) 

Make sure you don't remove the UPX from the release build.

For Release builds, you will require UPX.exe to be in the previous folder of your \DCX-master\
folder. If you don't package the release-build with UPX, mIRC won't load the DLL. I believe its
something to do with debug checking with NDEBUG as well as possible optimizations.

If you don't have .git installed, you will have issues with 
` #include "gitbuild.h" ` in defines.h 

This file is only 5 lines, 
```
// gitbuild.h --- Auto Generated resource header, DO NOT EDIT! 
#pragma once 
#define GIT_DATE TEXT("2014-01-19 20:43:29 +0000") 
#define GIT_HASH TEXT("768dbb38ca2cda55283c3961313d44fc364debea") 
#define GIT_DESCRIBE TEXT("2.0-3-g768dbb3")  
```
and then add gitbuild.h to your project folder.

you could alternatively just set those options manually in defines.h

or if you download git, you will have to clone the repository, and run
the \sourcecontrol  solution file from Visual Studio, this builds the github.h file.

Having git installed, and running the \sourcecontrol doesn't work either, as its 
looking for .git files only found in the cloned repository.

Some of this might seem straight forward to people who are familiar with git
and version control, so perhaps this will be useful to beginners.

**Comment by twig** [comment]
For a second I thought it was instructions on how to compile the DCX docs lol
