### ISSUE TITLE
mIRCLinker bugs

### ISSUE THREAD

**Issue by Loveness** [twig/dcxdll#13]
I use DCX 2.0 Build 1120 and all dialogs are working fine, no errors occur and on the latest version 3.1 from GitHub, when i open a dialog, click it or even i change mouse in this dialog etc. sometimes the following errors occur;

D_ERROR mIRCLinker::eval() (SendMessage() - failed)

I don't know what mIRCLinker does, but will be good if this mIRCLinker will be removed totally :)

P.S. "Enable SendMessage Server" in mIRC is enabled. Using mIRC 7.47 version

**Comment by OokEek** [comment]
It should return a more indepth error message than that, what else does it say?

**Comment by Loveness** [comment]
No other errors returns.. only this line:

D_ERROR mIRCLinker::eval() (SendMessage() - failed)
I have many dialogs created using only DCX (I don't use MDX or something else).. I use only DCX. So depeing the dialog and event, sometimes returns this error and no other errors return. I give an example of a short dialog where this error occur even on mouse move:

Ooooops!!!! I found the bug he he.. this bug happens when you HALT or in script events, alias you have HALT anywhere.. especially in cb_alias. So let's give you the code of my dialog and cb_alias:

```
dialog icon {
  title $lang(422)
  size -1 -1 $iif($theme == standart,145,142) $iif($theme == standart,76,80)
  option dbu
}
alias icon $iif($dialog(icon),dialog -v icon,dialog -m icon icon)
**alias cb_icon {
  if ($2 == sclick) {
     ...
  }
    ...
}**
on 1:dialog:icon:init:*: {
    dcx Mark icon cb_icon
    ...
}
```

So, if I use instead of cb_icon this code:

> **alias cb_icon {
>   if ($2 == sclick) {
>      ...
>   }
>    halt
> }**

so on every event i meet error: D_ERROR mIRCLinker::eval() (SendMessage() - failed)

And one more thing:

If i use in this alias for example: if ($me != Sash) halt or i create an another subalias in it where HALT is present, depeing the event occur (sclick, mouseenter, dclick etc.) the error return: D_ERROR mIRCLinker::eval() (SendMessage() - failed)

I need to delete all HALT from all scripts and to modiy anyway where DCX is used or interfere to not make this error:  D_ERROR mIRCLinker::eval() (SendMessage() - failed)

So you have to make a thing that mIRCLinker to occur HALT mirc command in scripts. If there are no way to fix it, will be bad :( 

I'll be soon whit another issue.

**Comment by Loveness** [comment]
I don't understand, what this mIRCLinker does? :) I see no difference, excepts this error that brings bugs and discomfort :)

**Comment by OokEek** [comment]
the /halt command is considered an error condition in msl, & should be avoided whenever possible.
Most of the time what you really wanted to use was /return
