### ISSUE TITLE
$xdid(dialog,id).seltext comboex error

### ISSUE THREAD

**Issue by Loveness** [twig/dcxdll#16]
Having code:

```
xdialog -c themes 2 comboex 95 46 180 120 dropdown
xdid -a themes 2 0 0 0 0 0 Standard
xdid -a themes 2 0 0 0 0 0 Dark
xdid -c themes 2 2
```

When I execute:

//echo -a $xdid(themes,2).sel returns 2
//echo -a $xdid(themes,2,$xdid(themes,2).sel).text returns Dark
//echo -a $xdid(themes,2).seltext returns the following error:

```
D_ERROR $xdid ("themes 2 seltext" error: Invalid Item)
$xdid([dialog],[ID](,options)).prop
[dialog] = the dialog containing the control
[ID] = the ID of the control to affect
(options) = depends on the prop used
[prop] = depends on the control type
```

Tested on mIRC 7.48 with the latest 3.1-162. On 2.0.0 Build 1120 works fine.

**Comment by OokEek** [comment]
fixed.
Small change in code messed it up at some point :/
