### ISSUE TITLE
Have a suggestion to turn on/off error DCX messages

### ISSUE THREAD

**Issue by Loveness** [twig/dcxdll#17]
I have a suggestion to add a command, for example: /dcx errors on|off to enable/disable echo of DCX errors. I understand maybe is not so rentable, but it helps in most important cases. For example, I need to disable D_ERROR mIRCLinker::eval() (SendMessage() - failed) when a /halt command occurs. I tried somehow to resolve this issue to delete the error line from Status Window or to halt this messages and nothing helps (was added a suggestion in mIRC forum to add /rline,/dline,/aline to work not only for custom windows, but also for status window, channels and query windows.. Khaled not answered yet to this suggestion).

I understand that I can replace all /halt commands with /return etc. but, as I said, I have tons of code :( I want to add the latest dcx.dll to my mIRC Korona script, because it works very good, but I don't want to change all the codes to avoid /halt command.

Thanks.

**Comment by OokEek** [comment]
Can't change how mIRC returns after a /halt
