### ISSUE TITLE
Line text bug!

### ISSUE THREAD

**Issue by Loveness** [twig/dcxdll#19]
Having this code:

```
xdialog -c nickmod 10 line 0 260 255 15
xdid -t nickmod 10 Text here:
xdid -f nickmod 10 +b ansi 7 Tahoma
```

in the 3.1 (162) version does not set the text in line. I've tried to set transparent, center or notheme and no results, i. e. the line appears, but without any text (no errors return). In 2.0 version everything works.

**Comment by OokEek** [comment]
For some reason the wrong command was used to get the text tokens, don't know why that was changed.
Fixed!
