### ISSUE TITLE
Scroll control creation is bugged

### ISSUE THREAD

**Issue by Dazuzi** [twig/dcxdll#29]
Scroll control creation is bugged with mIRC 7.66 and DCX 3.1-git394.

```
alias test dialog -m test test

dialog test {
  size -1 -1 400 400
}

on *:dialog:test:init:0: {
  dcx Mark $dname test_
  xdialog -c $dname 1 scroll 10 10 100 20
}

alias test_ echo -a Callback: $1-
```

Results in:
>D_CERROR xdialog -c test: Unable To Create Control (Unable To Create Window)
>Callback: test error 0 dialog none -c Unable To Create Control (Unable To Create Window)
>D_ERROR /xdialog ("test -c 1 scroll 10 10 100 20" error: Unable To Create Window)
>/xdialog -[switch] [dialog] [options]
>[switch] = a,b,c,d,E,f,g,h,j,l,m,n,P,q,r,R,s,S,t,T,U,V,w,x,z
>[dialog] = the dialog to affect
>[options] = depends on the switch used

**Comment by OokEek** [comment]
The wrong class name was being registered, this has been fixed now.

Thx for catching this :)
