### ISSUE TITLE
CLA issue with left indent (space) when resizing dialog

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#31]
I am using "**mIRC v7.66**" + "**DCX dll v3.1-git394**" in system "Windows 8.1 x64".

When I try to stretch the dialog with the mouse, then the left side of the element (green square) with an indent (space) from the edge sticks to the left edge of the dialog. This problem was not present in previous versions of dll. I would like to see a fix for this problem so that all assigned dimensions for margin maintain their proportions when the window is resized in all directions.

If I am doing something wrong, please tell me how to make this is it work correctly.

📷 [Screenshot](https://i.ibb.co/7SND75c/CLA-test.png)

Here is a test piece of script to reproduce this the problem. To run the script click on "**F5**" or enter the command "**/cla_test**":

```
alias F5 { cla_test }
alias cla_test {
  if ($dialog(cla_test)) .dialog -x cla_test
  else { .dialog -m cla_test cla_test }
}
dialog cla_test {
  title "CLA test"
  icon $mircexe,0
  option pixels
  size -1 -1 200 200
}
on *:DIALOG:cla_test:init:*:{
  .dcx Mark $dname cla_test_work
  .xdialog -b $dname +tyz
  .xdialog -g $dname +b $rgb(20,20,27)
  .xdialog -c $dname 1 panel 20 20 150 150
  .xdid -C $dname 1 +b $rgb(95,148,34)
  .xdialog -l $dname root $chr(9) +p 0 0 0 0
  .xdialog -l $dname cell root $chr(9) +li 1 1 0 0
  .xdialog -l $dname space 1 $chr(9) + 20 20 20 20
}
alias cla_test_work {}
```

**Comment by OokEek** [comment]
The value for the left border was always being set to zero, fixed.
remember & call ".timer 1 0 xdialog -l $dname update" at the end of the init event when doing cla.
