### ISSUE TITLE
Support for working in the AdiIRC client

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#32]
As of today, this does not work with **[AdiIRC](https://adiirc.com/)** Apparently because of the strict binding of DLL only for work in **mIRC** dialogs. I would like such support to appear in the near future as an alternative, to be able to use this DLL at the same time both in **mIRC** and in such a good analogue as the **[AdiIRC](https://adiirc.com/)** client. Both of these programs use the same "mSL" scripting language.

If it is possible to do this make, then I will wait for an update where such extended support will be added. Thanks.

**Comment by westor7** [comment]
Already suggested on #7 , AdiIRC is much better IRC client and i also wish to see that DLL supported there.
