### ISSUE TITLE
Line - visual mismatch in the size of the thickness in pixels

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#33]
I am using "**mIRC v7.66**" + "**DCX dll v3.1-git394**" in system "Windows 8.1 x64".

For a convenient demonstration, I created 10 lines that intersect each other horizontally and vertically and look like 5 crosses. At each subsequent intersection in the form of a cross, the size of the thickness of the lines increases by 1 pixel, and an obvious discrepancy in the thickness between the horizontal and vertical lines becomes visible. In addition, can see that the very first horizontal line with the specified size of 1 pixel in height (thickness) is not displayed at all. And only when the thickness of both lines reaches 4 pixels, then the fourth cross looks evenly created from lines of the same thickness, while the 5th cross is no different from the 4th, because further increase in the size of the lines by 1 pixel - does not bring any result.

I don't know if it was intended that way or if it was a simple calculation error or maybe it's a systemic problem, but I noticed it and decided to report it here. It would be nice to be able to create the same lines of any size without restrictions.

📷 [Screenshot](https://i.ibb.co/G7xWTbT/Line-test.jpg)

Here is a test piece of script to reproduce this the problem. To run the script click on "**F5**" or enter the command "**/line_test**":

```
alias F5 { line_test }
alias line_test {
  if ($dialog(line_test)) .dialog -x line_test
  else { .dialog -m line_test line_test }
}
dialog line_test {
  title "Line test"
  icon $mircexe,0
  option pixels
  size -1 -1 370 90
}
on *:DIALOG:line_test:init:*:{
  .dcx Mark $dname line_test_work
  .xdialog -b $dname +ty
  .xdialog -g $dname +b $rgb(20,20,27)
  .xdialog -c $dname 1 line 20 44 50 1
  .xdialog -c $dname 2 line 43 20 1 50 vertical
  .xdialog -c $dname 3 line 90 44 50 2
  .xdialog -c $dname 4 line 113 20 2 50 vertical
  .xdialog -c $dname 5 line 160 44 50 3
  .xdialog -c $dname 6 line 183 20 3 50 vertical
  .xdialog -c $dname 7 line 230 44 50 4
  .xdialog -c $dname 8 line 252 20 4 50 vertical
  .xdialog -c $dname 9 line 300 44 50 5
  .xdialog -c $dname 10 line 322 20 5 50 vertical
}
alias line_test_work {}
```

**Comment by OokEek** [comment]
A rounding issue was causing 1px horiz lines to have the size set to zero, fixed.
