### ISSUE TITLE
Divider - unable to append child control

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#46]
I am using "**mIRC v7.66**" + "**DCX dll v3.1-git394**" in system "Windows 8.1 x64".

I'm have tried to set the "**Panel**" control to the left side of the divider as a child control , but this doesn't work for some reason.
If I am doing something wrong, please explain what the problem might be. Thanks.

> `D_ERROR /xdid ("divider_test 1 -l 100 0 	 2 panel 0 0 100 100" error: Control with ID 2(4294961296) already exists)`

Here is a test piece of script to reproduce this the problem. To run the script click on "**F5**" or enter the command "**/divider_test**":

```
alias F5 { divider_test }
alias divider_test {
  if ($dialog(divider_test)) .dialog -x divider_test
  else { .dialog -m divider_test divider_test }
}
dialog divider_test {
  title "Divider test"
  icon $mircexe,0
  option pixels
  size -1 -1 500 400
}
on *:DIALOG:divider_test:init:*:{
  .dcx Mark $dname divider_test_work
  .xdialog -b $dname +ty
  .xdialog -g $dname +b $rgb(20,20,27)
  .xdialog -c $dname 1 divider 50 50 400 300 vertical
  .xdid -l $dname 1 100 0 $chr(9) 2 panel 0 0 100 100
}
alias divider_test_work {}
```

**Comment by OokEek** [comment]
Fixed it.
Was a bug in checking if an id was already in use.
