### ISSUE TITLE
Divider - new proposals to improve for updating

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#53]
I am using "**mIRC v7.66**" + "**DCX dll v3.1-git428**" in system "Windows 8.1 x64".

My proposals for what needs to be added in "Divider", to make it maximally functional and beautiful:

1. Customizable border thickness in pixels (only for `+b`). For example, through the command: "**/xdid -x $dname 1 +a 1**".
2. Customizable border color. For example, through the command: "**/xdid -C $dname 1 +a $rgb(255,0,0)**". 
3. Customizable divider line thickness between the fields in pixels.
4. Customizable divider line color between the fields.
5. Customizable default background color for control "Divider".

---

📷 [Screenshot](https://i.ibb.co/wp21fWJ/divider-test.jpg)

Here is a test piece of script to reproduce this the problem. To run the script click on "**F5**" or enter the command "**/divider_test**":

```
alias F5 { divider_test }
alias divider_test {
  if ($dialog(divider_test)) .dialog -x divider_test
  else { .dialog -m divider_test divider_test }
}
dialog divider_test {
  title "Divider test"
  icon $mircexe,0
  option pixels
  size -1 -1 500 400
}
on *:DIALOG:divider_test:init:*:{
  .dcx Mark $dname divider_test_work
  .xdialog -b $dname +ty
  .xdialog -g $dname +b $rgb(10,10,17)
  .xdialog -c $dname 1 divider 50 50 400 300 notheme | .xdid -v $dname 1 30
  .xdid -x $dname 1 +b
  .xdid -l $dname 1 30 0 $chr(9) 2 panel 0 0 0 0 | .xdid -C $dname 2 +b $rgb(25,25,25)
  .xdid -r $dname 1 0 0 $chr(9) 3 divider 0 0 0 0 vertical | .xdid -v $dname 3 300
  .xdid -l $dname 3 200 0 $chr(9) 4 divider 0 0 0 0 | .xdid -v $dname 4 235
  .xdid -r $dname 3 100 0 $chr(9) 5 panel 0 0 0 0 | .xdid -C $dname 5 +b $rgb(35,35,35)
  .xdid -l $dname 4 200 0 $chr(9) 6 panel 0 0 0 0 | .xdid -C $dname 6 +b $rgb(40,40,47)
  .xdid -r $dname 4 30 0 $chr(9) 7 panel 0 0 0 0 | .xdid -C $dname 7 +b $rgb(25,25,25)
}
alias divider_test_work {}
```

**Comment by OokEek** [comment]
The divider control its self is not meant to be seen except for the positioning bar, as such it has no border or background drawing.
I have added /xdid -Q & -W for setting the positioning bars colours & width.
