### ISSUE TITLE
Docked webctrl on a channel - Mouse Wheel Scroll Not Working

### ISSUE THREAD

**Issue by G3n7r0** [twig/dcxdll#6]
Hi,
as in the topic, I've created a docked webctrl on a channel, loaded a page and the mouse wheel scrolling on the page does not work. If I undock the control (dialog) mouse wheel scrolling starts to work.

I've skimmed through the xDock (UltraDock) code and noticed this:
"mIRCTEXT('s channel/query/status window')s scrollbar isnt a system scrollbar so these functions fail." 
is that the reason scrolling does not work?
Is there a fix, or a workaround so the scrolling works in the docked webctrl?

I'm using DCX (XPopup) DLL 2.0.1120 Development Build23 UTF, mIRC v7.32, Win7 x64.

Thanks.

**Comment by OokEek** [comment]
Please provide minimum code required to reproduce this bug.
