### ISSUE TITLE
DCX - add complete instruction for building a DLL file

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#60]
I am using "**Visual Studio Community 2019 v16.11.3**" in system "Windows 8.1 x64".

When trying to build a DLL, at least a few errors about missing files appear. Surely many have encountered similar problems and difficulties in assembling this project, and do not know how to fix it and what needs to be done:
> C1083 - `gitBuild.h`: No such file or directory
> C1083 - `GSL\gsl`: No such file or directory

This creates problems when testing the update in "dcxdll-master" to find bugs and quickly fix them, before the main release.

Many of the users of your project would like to receive a complete and detailed instruction on how to correctly assemble this project into a DLL file. This can be a list that should contain at least the following step-by-step instructions:

1. What development environment programs and their versions need to be installed.
2. What additional components and dependencies need to be installed.
3. What additional files may be needed, where to get them or how to create them manually.
4. Which project files should be selected and which menu items in the development environment should be clicked to start the correct DLL compilation process.
5. Where and to whom to contact for help and support in case of errors during the compilation of the project.

**Comment by OokEek** [comment]
This has been added to the docs.
