### ISSUE TITLE
List - incorrect behavior when the control style is enabled "multicol"

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#61]
I am using "**mIRC v7.67**" + "**DCX dll v3.1-git428**" in system "Windows 8.1 x64".

When set the control style `multicol`, when a line is selected, then in that part of the line with text that goes beyond the set boundaries of the column width, several text layers are superimposed on each other - it looks like a constant increase in bold font. Logically, this part of the line with the text should be hidden (not erased or cut off) beyond the set width of the column border and can be completely read by moving the cursor to the right and left.

If I am doing something wrong, please explain how to properly configure and use it. Thanks.

---

![image](https://i.ibb.co/0ZgK46s/list-test.jpg)

Here is a test piece of script to reproduce this the problem. To run the script click on "**F5**" or enter the command "**/list_test**":

```
alias F5 { list_test }
alias list_test {
  if ($dialog(list_test)) .dialog -x list_test
  else { .dialog -m list_test list_test }
}
dialog list_test {
  title "List test"
  icon $mircexe,0
  option pixels
  size -1 -1 300 255
}
on *:DIALOG:list_test:init:*:{
  .dcx Mark $dname list_test_work
  .xdialog -b $dname +ty
  .xdialog -g $dname +b $rgb(20,20,27)
  list_making $dname 1
}
alias -l list_making {
  .xdialog -c $1 $2 list 30 30 240 200 notheme multicol
  .xdid -x $1 $2 +b
  .xdid -m $1 $2 +w 100
  .xdid -C $1 $2 +b $rgb(40,40,47)
  .xdid -C $1 $2 +t $rgb(235,227,203)
  .xdid -f $1 $2 + ansi 10 Comic Sans MS
  var %i 1 | while (%i <= 10) {
    .xdid -a $1 $2 %i %i - Line of text to test
    inc %i
  }
}
alias list_test_work {}
```

**Comment by OokEek** [comment]
fixed.
