### ISSUE TITLE
Image - reusing the command to start the animation causes a crash error

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#67]
I am using "**mIRC v7.67**" + "**DCX dll v3.1-git469**" in system "Windows 8.1 x64".

After creating a control "Image", in which automatically an animated image in the "GIF" format is launched, if used once or re-enter the command "**/xdid -F $dname 1 +a 1**", then an crash error occurs after which the work of the mIRC client shutdown.

Would like to see a fix for this problem. Thanks.

---

![image](https://i.ibb.co/bPVdW8p/image-crash.jpg)

Here is a test piece of script to reproduce this the problem. To run the script click on "**F5**" or enter the command "**/image_test**":

```
alias F5 { image_test }
alias image_test {
  if ($dialog(image_test)) .dialog -x image_test | else { .dialog -m image_test image_test }
}
dialog image_test {
  title "Image test"
  icon $mircexe,0
  option pixels
  size -1 -1 450 300
}
on *:DIALOG:image_test:init:0:{
  .dcx Mark $dname image_test_work
  .xdialog -b $dname +ty
  .xdialog -g $dname +b $rgb(20,20,27)
  .xdialog -c $dname 1 image 30 25 390 250 notheme 
  .xdid -x $dname 1 +b
  .xdid -S $dname 1 1
  .xdid -C $dname 1 +b $rgb(40,40,47)
  var %image_path image\gif\file1.gif
  if ($exists(%image_path)) .xdid -i $dname 1 +abh %image_path
  .xdid -F $dname 1 +a 1
}
alias image_test_work {}
```

**Comment by OokEek** [comment]
Fixed.
