### ISSUE TITLE
Porting to AdiIRC

### ISSUE THREAD

**Issue by tbs** [twig/dcxdll#7]
Hey, someone here is interested to port the dll to **AdiIRC**?

If you don't know, or just back recently from a Mars trip, **AdiIRC** is a free irc client and, the first _alternative_ to **mIRC** to supporting **MSL** (work in progress).

Official website: http://www.adiirc.com/

If you mind to try that, I suggest to use the beta development build (type **/betaup** in client).

The dev changelog is here: http://adiirc.com/changelog.php

You can contact the author in it's official channel **#AdiIRC** @ **irc.nordicirc.com** if need to clarify any question.

Thanks!

**Comment by OokEek** [comment]
AdilIRC website says it only loads 64bit dlls on win64 even if using the 32bit exe, & will only load mIRC dlls like dcx on win32.
Not something i intend messing with any time soon.
