### ISSUE TITLE
Image - add a new control styles and information for to help documentation

### ISSUE THREAD

**Issue by EpicNet** [twig/dcxdll#70]
I am using "**mIRC v7.67**" + "**DCX dll v3.1-git469**" in system "Windows 8.1 x64".

My proposals for what needs to be corrected and added in "Image", to make it maximally functional and beautiful:

1. Add new style `hcenter` to align the image horizontally inside the control, when using the flag `+k` (for aspect ratio).
2. Add new style `vcenter` to align the image vertically inside the control, when using the flag `+k` (for aspect ratio).
3. Add information about the flag `+k` for the command "**/xdid -i dcx 4 +k [file]**" to the help documentation.
4. Add information about the flag `+A` for the command "**/xdid -i dcx 4 +A [file]**" to the help documentation.

---

On the left is how it looks now, and on the right is how it could be after the update:

![image](https://i.ibb.co/8PQWWdQ/image-hcenter.png)

Here is a test piece of script to reproduce this the problem. To run the script click on "**F5**" or enter the command "**/image_test**":

```
alias F5 { image_test }
alias image_test {
  if ($dialog(image_test)) .dialog -x image_test | else { .dialog -m image_test image_test }
}
dialog image_test {
  title "Image test"
  icon $mircexe,0
  option pixels
  size -1 -1 450 300
}
on *:DIALOG:image_test:init:0:{
  .dcx Mark $dname image_test_work
  .xdialog -b $dname +ty
  .xdialog -g $dname +b $rgb(20,20,27)
  .xdialog -c $dname 1 image 30 25 390 250 notheme 
  .xdid -x $dname 1 +b
  .xdid -S $dname 1 1
  .xdid -C $dname 1 +b $rgb(40,40,47)
  var %image_path image\gif\file2.gif
  if ($exists(%image_path)) .xdid -i $dname 1 +abhkA %image_path
}
alias image_test_work {}
```

---
Thanks for the fantastic improvements to your project. Don't stop there. We are waiting new updates! ⭐⭐⭐⭐⭐

**Comment by OokEek** [comment]
good idea, added it.
