### ISSUE TITLE
Null properties for some controls

### ISSUE THREAD

**Issue by Dazuzi** [twig/dcxdll#75]
Some properties of some controls can't be retrieved when using DCX 3.1-git469 with mIRC 7.68. 

```
alias test dialog -m test test

dialog test {
  size -1 -1 200 200
}

on *:dialog:test:init:0: {
  dcx Mark $dname test_
  xdialog -c $dname 1 button 10 10 100 40
  xdialog -c $dname 2 box 10 60 100 20
  xdialog -c $dname 3 check 10 110 100 20
  xdialog -c $dname 4 edit 10 110 100 20
  set -l %x 1
  while (%x <= 4) {
    echo -a ID: %x ISID: $xdialog(test,%x).isid TYPE: $xdid(test,%x).type POS: $xdid(test,%x).pos DPOS: $xdid(test,%x).dpos
    inc %x
  }
}

alias test_ noop
```
Results in:
>ID: 1 ISID: $true TYPE: button POS: 10 10 100 40 DPOS: 10 10 100 40
>ID: 2 ISID: $true TYPE: POS: DPOS:
>ID: 3 ISID: $true TYPE: POS: DPOS:
>ID: 4 ISID: $true TYPE: edit POS: 10 110 100 20 DPOS: 10 110 100 20

Not an exhaustive list of controls or properties, just the ones I came across.

**Comment by OokEek** [comment]
Fixed.
Caused by incomplete changes for new parseGlobalInfoRequest()

Let me know if is missed anything.
