### ISSUE TITLE
Can't add Item to rebar

### ISSUE THREAD

**Issue by Valfa** [twig/dcxdll#8]
I tried to change my old dcxdll to a newer one found somewhere a compiled v3 (3.0.166.1) .
After changing dll I get this error (id 1100 is a rebar element)

D_ERROR /xdid ("dcConf 1100 -a 0 + 0 200 0 0 16711680 Skripte && Module 	 1101 treeview 0 30 200 440 showsel hasbuttons haslines linesatroot" error: Control with ID "1101" already exists)

Then I tried to check if it really exists with 

//echo -s $xdid(dcConf, 1101).type

Dialog waqas still open, and I got

D_ERROR $xdid ("dcConf 1101 type" error: Invalid ID : 1101 (dialog dcConf))

changing back to my old dll and it works fine

**Comment by OokEek** [comment]
try the latest C++14 branch builds & let me know how it goes.
